sudo: required

services:
  - docker

before_install:
  - docker build -t shysan/react-test -f ./client/Dockerfile.dev ./client

#scripts for testing codebase
script:
  - docker run -e CI=true shysan/react-test npm test

after_success:
  - docker build -t shysan/multi-client ./client
  - docker build -t shysan/multi-nginx ./nginx
  - docker build -t shysan/multi-worker ./worker
  - docker build -t shysan/multi-server ./server
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to docker hub
  - docker push shysan/multi-client 
  - docker push shysan/multi-nginx
  - docker push shysan/multi-worker
  - docker push shysan/multi-server